# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='noteFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('contribAuthor', models.CharField(max_length=50)),
                ('zippedFile', models.FileField(upload_to='')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.noteDetails')),
            ],
        ),
    ]
