# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noteDetails',
            new_name='noteDetail',
        ),
        migrations.RenameModel(
            old_name='noteFiles',
            new_name='noteFile',
        ),
    ]
