# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20161228_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userDetails',
            new_name='profile',
        ),
    ]
