# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20161229_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
