# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20161231_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MEA', 'MEA')], max_length=3),
        ),
    ]
