# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20161231_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engg.'), ('ECE', 'Electronics and Comm. Engg.'), ('EEE', 'Electrical Engg.'), ('MEA', 'Mechanical Engg.')], max_length=3),
        ),
    ]
