# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], default='settings.MEDIA_ROOT/profile_pic/default.png', max_length=1),
        ),
    ]
