# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20161231_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
