# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_userprofile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedetail',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('MME', 'MME'), ('Chem', 'ChE'), ('Civil', 'Civil')], max_length=5),
        ),
    ]
