# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_userprofile_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zippedFile', models.FileField(upload_to='uploads/')),
                ('chapterName', models.CharField(max_length=50)),
                ('contribAuthor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='notefile',
            name='contribAuthor',
        ),
        migrations.RemoveField(
            model_name='notefile',
            name='zippedFile',
        ),
        migrations.AddField(
            model_name='chapters',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.noteFile'),
        ),
    ]
