# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_auto_20170105_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default_pic.jpg', upload_to='profile_pictures'),
        ),
    ]
