# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20170108_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='chapter_images/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.noteFile')),
            ],
        ),
    ]
