# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_auto_20170109_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='toBeDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
