# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_remove_userprofile_tobedeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='chapter_images/'),
        ),
    ]
