# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_auto_20170117_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picThumbnail',
            field=models.ImageField(default=1, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
